name: Test & Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 1.19
      uses: actions/setup-java@v4
      with:
        java-version: '19'
        distribution: zulu
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Create empty keystore
      run: echo "storeFile=/" > keystore.properties
    - name: Unit Tests
      run: ./gradlew testFullDebugUnitTest
    - name: Build with Gradle
      run: ./gradlew app:licenseFullDebug app:assembleFullDebug app:licensePlayStoreDebug app:assemblePlayStoreDebug wearOS:licenseDebug wearOS:assembleDebug
    - uses: actions/upload-artifact@v4
      with:
        name: app-full-debug.apk
        path: ./app/build/outputs/apk/full/debug/app-full-debug.apk
    - uses: actions/upload-artifact@v4
      with:
        name: app-playStore-debug.apk
        path: ./app/build/outputs/apk/playStore/debug/app-playStore-debug.apk
    - uses: actions/upload-artifact@v4
      with:
        name: wearOS-debug.apk
        path: ./wearOS/build/outputs/apk/debug/wearOS-debug.apk
    - name: KTLint
      if: always()
      run: ./gradlew ktlintCheck
